// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package openapi

// Defines values for OrderResponseStatus.
const (
	Completed     OrderResponseStatus = "completed"
	Pending       OrderResponseStatus = "pending"
	WaitingPickup OrderResponseStatus = "waitingPickup"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error   *string `json:"error,omitempty"`
	Message *string `json:"message,omitempty"`
}

// MenuItem defines model for MenuItem.
type MenuItem struct {
	Description *string `json:"description,omitempty"`
	Id          *string `json:"id,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// OrderResponse defines model for OrderResponse.
type OrderResponse struct {
	Id          *string              `json:"id,omitempty"`
	MenuItemId  *string              `json:"menu_item_id,omitempty"`
	MenuName    *string              `json:"menu_name,omitempty"`
	OrderNumber *int                 `json:"order_number,omitempty"`
	Status      *OrderResponseStatus `json:"status,omitempty"`
}

// OrderResponseStatus defines model for OrderResponse.Status.
type OrderResponseStatus string

// SimilarityRequest defines model for SimilarityRequest.
type SimilarityRequest struct {
	// AudioBase64 Base64-encoded audio data (required MP3 file)
	AudioBase64 string `json:"audio_base64"`

	// Text Text to compare against transcribed audio(文字起こし正解のテキスト)
	Text string `json:"text"`
}

// SimilarityResponse defines model for SimilarityResponse.
type SimilarityResponse struct {
	// Similarity Similarity score between 0 and 1 (1: perfect match, 0: no match)
	Similarity *float32 `json:"similarity,omitempty"`
}

// PostApiV1StoresOrdersJSONBody defines parameters for PostApiV1StoresOrders.
type PostApiV1StoresOrdersJSONBody struct {
	MenuItemId *string `json:"menu_item_id,omitempty"`
}

// PostApiV1StoresOrdersJSONRequestBody defines body for PostApiV1StoresOrders for application/json ContentType.
type PostApiV1StoresOrdersJSONRequestBody PostApiV1StoresOrdersJSONBody

// PostApiV1TranscriptJSONRequestBody defines body for PostApiV1Transcript for application/json ContentType.
type PostApiV1TranscriptJSONRequestBody = SimilarityRequest
