// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package openapi

// GetWsStayParams defines parameters for GetWsStay.
type GetWsStayParams struct {
	Room string `form:"room" json:"room"`
}
